services:
  postgres:
    image: postgres:16
    container_name: my_app_db
    restart: unless-stopped
    env_file:
      - .env.docker
    environment:
      POSTGRES_DB: my_hackathon_db
      POSTGRES_USER: myapp_user
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: my_app_backend
    restart: unless-stopped
    env_file:
      - .env.docker
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: my_app_frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://backend:3000
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  pg_data:
